#GET http://localhost:3000/api/diaries

#PUT http://localhost:3000/api/diaries

POST http://localhost:3000/api/diaries 
Content-Type: application/json

{
  "date": "11.04.2023",
  "weather": "god",
  "visibility": "good",
  "comment":"wetty and greeny"
}